# Site settings
title: Tomas Dosoudil
email: 
description: 
baseurl: "" 
url: ""
twitter_username: 
github_username:  tomdos

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
