
baseURL = "https://tomdos.github.io"
title = "Tomas Dosoudil"
languageCode = "en-us"
theme = "devise"
#relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2023, Tomas Dosoudil"

[markup]
  [markup.highlight]
    style = 'dracula'

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -90
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100

# Configuration Features
[params]
  description = "Tomas Dosoudil's blog"      # Your meta description of the site
  header_title = "Tomas Dosoudil"                 # Your header title
  header_subtitle = "A software engineer enthusiast" # Your header subtitle
  home_image = "me.jpg"          # Path to header image starting from the static directory
  recent_posts = 100                           # Max amount of recent posts to show
  mainSections = ["post"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/tomdos"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/tom%C3%A1%C5%A1-dosoudil-49453658/"
